### ISSUE TITLE
🎯[Feat] 연계된 일정 기능 구현

### ISSUE THREAD

**Issue by CJC0512** [OmokNoonE/PPM-backend#101]
### 기능 요약 (Feature Summary)
일정의 속성값이 변함에 따라 연계된 일정의 속성 또한 갱신 되는 기능

### 작업 내용 (Work Description)
> 개발 일정에 여유가 있을 경우 구현 예정

**[일정]**
1. 일정이 삭제될 경우
   - [ ] 하위 일정 삭제

2. 일정의 속성이 변동된 경우, 그 상위 혹은 하위 일정의 속성도 갱신되는 기능
    2-1. 일정의 기간이 변동된 경우, 
   - [ ] 공수가 갱신되는 기능
   - [ ] 상위 일정의 기간과 공수도 갱신되는 기능

   2-2. 일정의 가중치가 변동된 경우, 
   - [ ] 해당 가중치에 맞게 상위 일정의 진행률이 갱신되는 기능

   2-3. 일정의 진행률이 변동된 경우,
   - [ ] 상위 일정의 진행률도 갱신되는 기능

### 관련 이슈 (Related Issues)
- #71 

### 체크리스트 (Checklist)
- [ ] 새로운 기능에 대한 코드 작성 완료
- [ ] 테스트 완료
- [ ] 문서화 완료
- [ ] 리뷰 요청

**Comment by jlee38266** [comment]
참고 하겠습니다!

**Comment by CJC0512** [comment]
폐기
