### ISSUE TITLE
🔄️[Refactor] 프로젝트 구성원 관리 기능 수정

### ISSUE THREAD

**Issue by jlee38266** [OmokNoonE/PPM-backend#158]
### 리팩토링 대상 (Refactoring Target)
실제 화면에서 요구 하는 형태로 데이터를 전달 하기 위해 코드를 개선합니다.

### 리팩토링 이유 (Reason for Refactoring)
조회 기능에 필터링 기능이 필요하고, 전체적으로 코드를 일관성 있게 개선해야 합니다.

### 개선된 점 (Improvements)
코드 가독성 및 화면에 필요한 데이터를 넘겨줄 수 있습니다.

### 관련 이슈 (Related Issues)
- #14 
- #15 

### 체크리스트 (Checklist)
- [ ] 리팩토링 완료
- [ ] 테스트 완료
- [ ] 문서화 완료
- [ ] 리뷰 요청

**Comment by ms1011** [comment]
조회, 생성, 수정 부분 오류 및 클라이언트에 보여줘야 하는 값으로 변경
