### ISSUE TITLE
🔄️[Refactor] 1차 QA 후 일정 작업 목록

### ISSUE THREAD

**Issue by CJC0512** [OmokNoonE/PPM-backend#208]
- #198
- #206 

### 리팩토링 대상 (Refactoring Target)
[최종찬]
#### 일정 상세
- [x] 부모, 선행 일정 검색 시, 검색어가 비어있을 경우 해당 프로젝트의 일정 전체 조회
- [x] 이해관계자 추가 안되는 오류 수정
- [x] 이해관계자 삭제 오류 수정
  - ❗ 테스트 환경에서 원활히 되었으므로, 체크. 실제 배포 환경에서 확인 필요
- [x] 업무 조회 시, 업무, 요구사항 배열 초기화 (ex. 일정의 업무가 없는 경우, 과거 조회한 일정의 업무가 조회되는 현상)
- [x] 일정 등록 시, 시작일, 종료일 날짜 범위 오류 수정
- [x] 일정 등록 버튼, PM만 보이도록 설정
- [x] 일정 동작 진행 후, 모달 닫힌 후, 요청 진행 후 페이지 새로고침 (데이터 갱신을 위함)
- [x] 일정 상태에 따라 일정 시트 및 일정 상세에서 상태에 따른 색상 추가

#### @ms1011 할 일
- [ ] 요구사항맵 중복으로 추가되는 오류
- [x] 일정에 포함된 모든 도메인에 대하여 Order By 처리 확인
- [x] 일정에 포함된 모든 도메인에 대하여 isDeleted 처리 확인
- [x] 업무 추가 버튼이 수정 밖으로 나와 있도록
- [x] 일정 상태 변경 시, 자동으로 수정사유 작성 및 저장(일정까지 변동사항 적용)
- [x] 일정 등록 및 수정 시, 가중치 범위 설정

### 리팩토링 이유 (Reason for Refactoring)
[왜 해당 부분을 리팩토링해야 하는지 설명해주세요.]

### 변경 내용 (Changes Made)
[어떤 변경을 했는지 자세히 설명해주세요.]

### 개선된 점 (Improvements)
[리팩토링으로 인해 개선된 점을 설명해주세요.]

### 영향 (Impact)
[이 리팩토링이 시스템 전반에 미칠 영향에 대해 설명해주세요.]

### 관련 이슈 (Related Issues)
[관련된 이슈가 있다면 여기에 링크를 기재해주세요.]

### 체크리스트 (Checklist)
- [ ] 리팩토링 완료
- [ ] 테스트 완료
- [ ] 문서화 완료
- [ ] 리뷰 요청

**Comment by ms1011** [comment]
보류는 이제 제가!

**Comment by ms1011** [comment]
"요구사항맵 중복으로 추가되는 오류"는 추후에 따로 이슈 등록해서 수정
