### ISSUE TITLE
🎯[Feat] 프로젝트 구성원 역할 권한 기능 개발

### ISSUE THREAD

**Issue by jlee38266** [OmokNoonE/PPM-backend#33]
### 기능 요약 (Feature Summary)
- PM은 구성원에게 역할을 부여하고 수정할 수 있다.

### 작업 내용 (Work Description)
- PM은 구성원 추가 시에 역할을 부여할 수 있도록 코드를 작성한다.
- 역할은 프로젝트 내에서의 역할을 나타내며, 권한 설정을 포함한다.
- PM은 구성원의 역할을 수정할 수 있도록 코드를 작성한다.

### 관련 이슈 (Related Issues)
- 이슈 없음

### 체크리스트 (Checklist)
- [ ] 새로운 기능에 대한 코드 작성 완료
- [ ] 테스트 완료
- [ ] 문서화 완료
- [ ] 리뷰 요청"

**Comment by CJC0512** [comment]
관련 이슈 목록
- #46 
- #43 
- #48 
- #32
- #30
- #49
